title: Dan Rigs
author: Daniel Ridley
email: danriduk@gmail.com
description: ''
# social links
twitter_username:
github_username:  danriduk
baseurl: '/website'

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - blog.md
 - about.md
 - p5sketches.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

includes:
 - p5js
