# basic options
title: Dan Rigs
author: Daniel Ridley
email: danriduk@gmail.com
description:
twitter_username:
github_username:  danriduk
baseurl: "/home"
url: ""

# Build settings
markdown: kramdown
theme: minima
